export const SOCIAL_INTERACTIVE = {
  LIKE: 'LIKE',
  SHARE: 'SHARE',
  COMMENT: 'COMMENT',
  SAVE: 'SAVE',
  RANKING: 'RANKING',
  REPORT: 'REPORT',
};

export const POST_TYPES = {
  CREATED: 'CREATED',
  SHARED: 'SHARED',
  PAGE_NEW: 'PAGE_NEW',
  SERVICE: 'SERVICE',
  PAGE_REVIEW: 'PAGE_REVIEW',
  MY_MAP: 'MY_MAP',
  SHARE_PLAN: 'SHARE_PLAN',
  SERVICE_REVIEW: 'SERVICE_REVIEW',
  ACTIVITY: 'ACTIVITY',
};

export const INTERACTIVE = {
  CREATED: 'CREATED',
  SHARED: 'SHARED',
  SERVICE: 'SERVICE',
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
  PAGE_NEW: 'PAGE_NEW',
};
