export const TYPE_ORDER = {
  REQUEST: 'REQUEST',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
  CONFIRMED: 'CONFIRMED',
  AWAIT_CONFIRM: 'AWAIT CONFIRMATION',
  REQUESTING: 'REQUESTING',
  GOING_ON: 'GOING_ON',
  AWAIT_CANCEL: 'AWAIT_CANCEL',
};

export const VERIFY_PAGE_STATUS_TYPES = {
  REQUESTED: 'REQUESTED',
  COMPLETED: 'COMPLETED',
  REJECT: 'REJECT',
};

export const VERIFY_PAGE_TYPES = {
  IDENTITY_CARD: 'IDENTITY_CARD',
  PASSPORT: 'PASSPORT',
};

export const TOUR_TIME = {
  DAY: 'Day',
  NIGHT: 'Night',
};

export const VEHICLE = {
  BIKE: 'ICBIKE',
  CAR: 'ICCAR',
  PLANES: 'ICPLANES',
  MOTORCYCLE: 'ICMOTORCYCLE',
  TRAIN: 'ICTRAIN',
  SHIP: 'ICSHIP',
};

export const INCLUDES = {
  VEHICLE: 'ICVEHICLE',
  INSURRANCE: 'ICINSURRANCE',
  TOUR_GUIDE: 'ICTOURGUIDE',
  TICKET: 'ICTICKET',
  DRINK: 'ICDRINK',
  FOOD: 'ICFOOD',
};

export const FOOD_TYPES = {
  NORMAL: '0',
  NEW: '1',
  BESTSELLER: '2',
};

export const TASK_TYPES = {
  WHERE: 'WHERE',
  FOOD: 'FOOD',
  STAY: 'STAY',
  TOUR: 'TOUR',
  PAGE_NEW: 'PAGE_NEW',
};

export const TASKS_STATUS_TYPES = {
  COMPLETED: 'COMPLETED',
  INCOMPLETE: 'INCOMPLETE',
};

export const PLAN_TYPES = {
  COMPLETED: 'COMPLETED',
  DRAFT: 'DRAFT',
};

export const MY_MAP_TYPES = {
  SAVED: 'SAVED',
  HAD_CAME: 'HAD_CAME',
  WISH_CAME: 'WISH_CAME',
};

export const REPORT_STATUS_TYPES = {
  WAITING_FOR_PROCESSING: 'WAITING_FOR_PROCESSING',
  PROCESSING: 'PROCESSING',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
};

export const REPORT_TYPES = {
  USER: 'REPORT_USER',
  LOCATION: 'REPORT_LOCATION',
  POST: 'REPORT_POST',
  RANKING: 'REPORT_RANKING',
  PAGE: 'REPORT_PAGE',
  REPORT_ACTIVITY: 'REPORT_ACTIVITY',
};

export const STATUS_ORDER_TOUR = {
  REQUEST: 'REQUEST',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
};

export const TOUR_DETAIL_TYPES = {
  TOUR: 'TOUR',
  BOOKING: 'BOOKING',
  POST: 'POST',
  RANKING: 'RANKING',
  FOLLOW: 'FOLLOW',
  LOCATIONS: 'LOCATIONS',
  TICKET: 'TICKET',
  TIME: 'TIME',
  TRAVEL: 'TRAVEL',
};
