const Images = {
  background: require('./background.png'),
  logo: require('./logo.svg'),
  vi: require('./vi.svg'),
  en: require('./en.svg'),
  image_default: require('./image_default.png'),
  avatar_defautl: require('./avatarDefault.png'),
  user: require('./user.svg'),
  tour: require('./tour.svg'),
  food: require('./food.svg'),
  post: require('./post.svg'),
  noData: require('./noData.png'),
  sort: require('./sort.png'),
  noDisplay: require('./not_display.png'),
  sos: require('./sos.png'),
  marker: require('./marker.svg'),
  shield: require('./shield.svg'),
  onShield: require('./onShield.svg'),
  onLock: require('./onLock.svg'),
  onUnLock: require('./onUnLock.svg'),
  onDel: require('./onDel.svg'),
  onEdit: require('./onEdit.svg'),
  icon_food: require('./icon_food.svg'),
  icon_tour: require('./icon_tour.svg'),
  icon_where: require('./icon_where.svg'),
  icon_stay: require('./icon_stay.svg'),
  publish: require('./publish.svg'),
  unPublish: require('./unPublish.svg'),
  admin: require('./admin.svg'),
  onBlockIP: require('./onBlockIP.svg'),
  bell: require('./bell.svg'),
  mod: require('./mod.svg'),
  login_animation: require('./jGooooo_Animation.mp4'),
  form_login: require('./webadmin.png'),
  login_title: require('./login_title.png'),
  jGooooo_account: require('./jGooooo_account.svg'),
};
export default Images;
