export const LIST = [
  {
    id: 1,
    name: 'Admin',
    count: '1',
  },
  {
    id: 2,
    name: 'Chuyên viên xây dựng nội dung',
    count: '12',
  },
  {
    id: 3,
    name:
      'Chuyên viên kiểm duyệt nội dung, xử lý báo cáo và phản hồi của người dùng',
    count: '34',
  },
  {
    id: 4,
    name: 'Chuyên viên quản lý nhà cung cấp dịch vụ',
    count: '7',
  },
  {
    id: 5,
    name: 'Chuyên viên Quản lý người dùng',
    count: '17',
  },
];

export const DECENTRALIZATION = [
  {
    icon: 'fas fa-map-marker-alt',
    category: 'Địa điểm',
    detail: true,
    edit: true,
    delete: true,
    create: false,
    unBlock: true,
    block: true,
  },
  {
    icon: 'fas fa-bed',
    category: 'Dịch vụ chỗ nghĩ',
    detail: true,
    edit: true,
    delete: false,
    create: true,
    unBlock: false,
    block: true,
  },
  {
    icon: 'fas fa-flag',
    category: 'Trang Tour',
    detail: true,
    edit: true,
    delete: true,
    create: false,
    unBlock: true,
    block: true,
  },
  {
    icon: 'fas fa-utensils',
    category: 'Địa điểm ăn uống',
    detail: true,
    edit: true,
    delete: true,
    create: false,
    unBlock: true,
    block: true,
  },
  {
    icon: 'fas fa-star',
    category: 'Hoạt đông, sự kiện',
    detail: false,
    edit: true,
    delete: true,
    create: true,
    unBlock: false,
    block: false,
  },
  {
    icon: 'fas fa-file-alt',
    category: 'Bài viết',
    detail: true,
    edit: true,
    delete: true,
    create: false,
    unBlock: true,
    block: true,
  },
  {
    icon: 'fas fa-comment',
    category: 'Phản hồi',
    detail: false,
    edit: true,
    delete: true,
    create: true,
    unBlock: true,
    block: false,
  },
  {
    icon: 'fas fa-user-friends',
    category: 'Người dùng',
    detail: false,
    edit: true,
    delete: false,
    create: true,
    unBlock: true,
    block: true,
  },
  {
    icon: 'fas fa-cog',
    category: 'bg bài biết không hình',
    detail: true,
    edit: true,
    delete: true,
    create: true,
    unBlock: false,
    block: true,
  },
  {
    icon: 'fas fa-comment-dots',
    category: 'Tin nhắn hệ thống',
    detail: true,
    edit: false,
    delete: true,
    create: false,
    unBlock: false,
    block: false,
  },
];
